### ISSUE TITLE
Questions about TrajGAIL's code

### ISSUE THREAD

**Issue by ilikeface** [benchoi93/TrajGen_GAIL#1]
Dear author,
      Recently I have been reading your paper "TrajGAIL: Generating Urban Vehicle Trajectories using Generative  Adversarial Imitation Learning".At the same time, I downloaded the code of this paper on GitHub. The program works well when running behavioral cloning and inverse reinforcement learning models.But there was an error when I ran the GAIL model with the path scripts/ Gail/run_GAIL.py.
    Specifically, when I run run_gail.py, GAILRNN calls the unroll_trajectory2 function. The unroll_trajectory2 function initializes a number of variable definitions for observed and unobservable states. The statement "state = np_find_state(notdone_obs)" is then used to convert observable and unobservable states to belief states.
    However, the statement "state = np_find_state(notdone_obs)" keeps returning an error: "valueError: 0 is not in list".
    I don't know how to solve it, so I want to ask for your help.
    Thanks!
![Incorrect results](https://user-images.githubusercontent.com/52017843/119501115-24ce1c00-bd9b-11eb-8017-9403cec0484a.png)

**Comment by benchoi93** [comment]
Sorry for your inconvenience.
I previously made some modifications to some of the scripts, but did not update some of the scripts that might have some interactions, and this resulted in the version mismatch between codes.
I updated the GAIL module and checked on my local machine.
Can you try to run it again?

refer to the recent commit

FYI
the problem was that it tried to find "0" which was initially the start token.
I changed this to "1000" when testing a larger network and this was causing the problem.
and now unroll_trajectory2(unroll_batch) use self.env.start to use the predefined value.

**Comment by ilikeface** [comment]
Thank you for your reply.
The GAIL module is now up and running.
Many Thanks.

**Comment by ilikeface** [comment]
Thank you for your reply.
The GAIL module is now up and running.
Many Thanks.
